version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  prepare:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}
      - run:
          name: "Install Chrome"
          command: choco install googlechrome --version 79.0.3945.130
      - run:
          name: "Install project dependencies"
          command: >
              cd ./Framework2/;
              dotnet.exe restore;
              nuget restore;
      - save_cache:
          paths:
            - C:\Users\circleci\project\Framework2\UnitTestProject\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}

  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: "Run Build step"
          command: >
              cd ./Framework2/;
              dotnet.exe publish -c Release -r win10-x64

  test:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: "Tests"
          command: cd ./Framework2/; ./Test.bat
      - store_artifacts:
          path: ./Framework2/Test.bat

workflows:
  version: 2
  commit:
    jobs:
      - build
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
    jobs:
      - prepare
      - build
      - test
