version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  prepare:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - nuget-packages-v1-{{ arch }}-{{ .Branch }}-{{ checksum "packages.config" }}
            - nuget-packages-v1-{{ arch }}-{{ .Branch }}
            - nuget-packages-v1
      - run:
          name: "Install Chrome"
          command: choco install googlechrome --version 79.0.3945.130
      - run:
          name: "Install project dependencies"
          command: >
              cd ./Framework2/;
              dotnet.exe restore;
              nuget restore;
      - save_cache:
          paths:
            - C:\Users\circleci\project\Framework2\UnitTestProject\.nuget\packages
          key: nuget-packages-v1-{{ arch }}-{{ .Branch }}-{{ checksum "packages.config" }}

  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: "Run Build step"
          command: >
              cd ./Framework2/;
              dotnet.exe publish -c Release -r win10-x64
      - save_cache:
          paths:
            - C:\Users\circleci\project\Framework2\UnitTestProject\.dist\cached
          key: build-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

  test:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - restore_cache:
          keys:
            - build-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - build-v1-{{ arch }}-{{ .Branch }}
            - build-v1
      - run:
          name: "Tests"
          command: cd ./Framework2/; ./Test.bat
      - store_artifacts:
          path: ./Framework2/Test.bat

workflows:
  version: 2
  commit:
    jobs:
      - prepare
      - build:
        requires: 
          - prepare
      - test:
        requires: 
          - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - prepare
      - build:
        requires: 
          - prepare
      - test:
        requires: 
          - build
