version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}
      - run:
          name: "Test directory"
          command: ls
      - run:
          name: "Install project dependencies"
          command: >
              cd $PROJECT_PATH;
              dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\Framework2\UnitTestProject\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}
      - run:
          name: "Run Build step"
          command: >
              cd $PROJECT_PATH;
              dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\UnitTestProject.exe
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\UnitTestProject.exe