version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: "Install project dependencies"
          command: >
              cd ./Framework2/;
              dotnet.exe restore;
              nuget restore;
      - save_cache:
          paths:
            - C:\Users\circleci\project\Framework2\UnitTestProject\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "UnitTestProject.csproj" }}
      - run:
          name: "Run Build step"
          command: >
              cd ./Framework2/;
              dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Tests"
          command: cd ./Framework2/; ./Test.bat
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\UnitTestProject.exe